### ISSUE TITLE
BlobContainer.h/dxbcutils.h missing

### ISSUE THREAD

**Issue by celestil** [microsoft/D3D9On12#15]
I have to verify if the D3D9on12 patch fixes my issue, then I tried to build D3D9on12 on VS 2019. However, there're some header files missing. Could you please help tell me where to find them? Thanks

Severity Code Description Project File Line Suppression State
Error (active) E1696 cannot open source file "BlobContainer.h" d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\include\DxbcBuilder.hpp 2
Error (active) E1696 cannot open source file "BlobContainer.h" d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 4
Error (active) E0020 identifier "DXBCFourCC" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\include\DxbcBuilder.hpp 56
Error (active) E0020 identifier "CDXBCParser" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\include\DxbcBuilder.hpp 60
Error (active) E0020 identifier "DXBCFourCC" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\include\DxbcBuilder.hpp 60
Error (active) E0020 identifier "DXBCBlobHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\include\DxbcBuilder.hpp 77
Error (active) E0020 identifier "DXBCHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 14
Error (active) E0020 identifier "DXBCFourCC" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 51
Error (active) E0020 identifier "DXBCBlobHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 66
Error (active) E0020 identifier "DXBC_MAX_SIZE_IN_BYTES" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 73
Error (active) E0020 identifier "CDXBCParser" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 124
Error (active) E0020 identifier "DXBCFourCC" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 124
Error (active) E0020 identifier "DXBC_BLOB_NOT_FOUND" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 130
Error (active) E0020 identifier "DXBCHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 167
Error (active) E0020 identifier "pHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 167
Error (active) E0029 expected an expression d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 167
Error (active) E0065 expected a ';' d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 167
Error (active) E0020 identifier "DXBCBlobHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 169
Error (active) E0020 identifier "pNextBlobHeader" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 169
Error (active) E0029 expected an expression d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 169
Error (active) E0029 expected an expression d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 179
Error (active) E0020 identifier "DXBC_FOURCC_NAME" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 187
Error (active) E0020 identifier "DXBC_MAJOR_VERSION" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 188
Error (active) E0020 identifier "DXBC_MINOR_VERSION" is undefined d3d12translationlayer_wdk.lib (_deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib) - windows-default C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 189
Error C1083 Cannot open include file: 'BlobContainer.h': No such file or directory C:\Users\celestil\D3DGFx\out\build\windows-default\D3DGFx C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\DxbcBuilder.cpp 4
Error C1083 Cannot open include file: 'dxbcutils.h': No such file or directory C:\Users\celestil\D3DGFx\out\build\windows-default\D3DGFx C:\Users\celestil\D3DGFx\D3D12TranslationLayer\src\ShaderParser.cpp 6
Error C1083 Cannot open include file: 'BlobContainer.h': No such file or directory C:\Users\celestil\D3DGFx\out\build\windows-default\D3DGFx C:\Users\celestil\D3DGFx\D3D9On12\include\pch.h 22

**Comment by jenatali** [comment]
It seems you're somehow missing the DXBCParser project. That should be included as part of the D3D12TranslationLayer component: https://github.com/microsoft/D3D12TranslationLayer/tree/master/DxbcParser.

My build looks like:
![image](https://user-images.githubusercontent.com/17788890/141652793-418198f4-9a6b-45da-bfb2-adf21cb2c67f.png)

**Comment by celestil** [comment]
Thanks,

Then I got another build error. packages\WinPixEventRuntime.1.0.190604001\build\WinPixEventRuntime.targets.lib not exists. Could you please shed a light on this?

Thanks
Celesti

  [58/58] Linking CXX shared library D3D9On12\src\d3d9on12.dll
  FAILED: D3D9On12/src/d3d9on12.dll D3D9On12/src/d3d9on12.lib
  cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_dll --intdir=D3D9On12\src\CMakeFiles\d3d9on12.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo D3D9On12\src\CMakeFiles\d3d9on12.dir\cmake_pch.cxx.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Adapter.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12AppCompat.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Blit.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Constants.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12DDIStub.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12DecodeDevice.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Device.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Draw.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12FastUploadAllocator.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Fence.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12InputAssembly.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12InputLayout.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12PipelineState.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12PipelineStateCache.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12PixelStage.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Query.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Resource.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Shader.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12SwapChain.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12VertexStage.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12VideoDevice.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12VideoProcessDevice.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\d3d9on12.rc.res  /out:D3D9On12\src\d3d9on12.dll /implib:D3D9On12\src\d3d9on12.lib /pdb:D3D9On12\src\d3d9on12.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /DEF:C:\Users\celestil\D3DGFx\D3D9On12\src\d3d9on12.def  /DELAYLOAD:dxcore.dll /ignore:4286 /DEF:..\..\..\D3D9On12\src\d3d9on12.def  _deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib  D3D9On12\ShaderConverter\d3d9on12_shaderconv.lib  _deps\d3d12translationlayer-build\src\d3d12translationlayer.lib  d3d12.lib  dxgi.lib  atls.lib  dxcore.lib  packages/WinPixEventRuntime.1.0.190604001/build/WinPixEventRuntime.targets.lib  _deps\d3d12translationlayer-build\DxbcParser\dxbcparser.lib  packages/Microsoft.Direct3D.DxbcSigner.1.0.0/build/native/Microsoft.Direct3D.DxbcSigner.targets.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
  LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo D3D9On12\src\CMakeFiles\d3d9on12.dir\cmake_pch.cxx.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Adapter.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12AppCompat.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Blit.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Constants.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12DDIStub.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12DecodeDevice.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Device.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Draw.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12FastUploadAllocator.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Fence.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12InputAssembly.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12InputLayout.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12PipelineState.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12PipelineStateCache.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12PixelStage.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Query.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Resource.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12Shader.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12SwapChain.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12VertexStage.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12VideoDevice.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\9on12VideoProcessDevice.cpp.obj D3D9On12\src\CMakeFiles\d3d9on12.dir\d3d9on12.rc.res /out:D3D9On12\src\d3d9on12.dll /implib:D3D9On12\src\d3d9on12.lib /pdb:D3D9On12\src\d3d9on12.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /DEF:C:\Users\celestil\D3DGFx\D3D9On12\src\d3d9on12.def /DELAYLOAD:dxcore.dll /ignore:4286 /DEF:..\..\..\D3D9On12\src\d3d9on12.def _deps\d3d12translationlayer-build\src\d3d12translationlayer_wdk.lib D3D9On12\ShaderConverter\d3d9on12_shaderconv.lib _deps\d3d12translationlayer-build\src\d3d12translationlayer.lib d3d12.lib dxgi.lib atls.lib dxcore.lib packages/WinPixEventRuntime.1.0.190604001/build/WinPixEventRuntime.targets.lib _deps\d3d12translationlayer-build\DxbcParser\dxbcparser.lib packages/Microsoft.Direct3D.DxbcSigner.1.0.0/build/native/Microsoft.Direct3D.DxbcSigner.targets.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:D3D9On12\src\CMakeFiles\d3d9on12.dir/intermediate.manifest D3D9On12\src\CMakeFiles\d3d9on12.dir/manifest.res" failed (exit code 1104) with the following output:
C:\Users\celestil\D3DGFx\out\build\windows-default\LINK : fatal error LNK1104: cannot open file 'packages\WinPixEventRuntime.1.0.190604001\build\WinPixEventRuntime.targets.lib'
  ninja: build stopped: subcommand failed.
