### ISSUE TITLE
Get IDXGISwapchain for a given IDirect3DSwapChain9 instance.

### ISSUE THREAD

**Issue by knk190001** [microsoft/D3D9On12#23]
I would like to render directx9 content in a SwapChainPanel via D3D9On12, but I can't seem to figure out how to get access to the IDXGI_Swapchain. Is there any way to get the IDXGI_Swapchain for a given IDirect3DSwapChain9? If not, could you consider adding this as a feature.

**Comment by jenatali** [comment]
This isn't something that's really doable. D3D9On12 does not always use DXGI swapchains (the version inside of Windows uses a slightly different mechanism), and even when it does, they're all HWND-based swapchains which can't be bound to a SwapChainPanel. To do what you're looking for here, you'd want to use D3D9On12 to render offscreen, and then use D3D12 to copy that offscreen-rendered content into a DXGI swapchain for the SwapChainPanel.
