### ISSUE TITLE
Halo Custom Edition with Open Sauce crashes almost instantly

### ISSUE THREAD

**Issue by Danfun64** [microsoft/D3D9On12#53]
I don't know if this is the right place to post this. I am using Windows 11 Home Edition 21H2 22000.1042 on my laptop. It has an iGPU with Intel Iris Xe and a dGPU with Nvidia Geforce RTX 3050 Ti. I have read that Intel Iris Xe has removed true D3D9 support in favor of this module, not sure if this is true on Nvidia's end.

After installing the mod Open Sauce 4.0 onto a copy of Halo Custom Edition, I have found that when opening the game, it loads for a couple seconds and then silently crashes to the desktop. This occurs regardless of whether I have it set to render using the integrated graphics or the dedicated graphics. This crash does not occur if Open Sauce 4.0 is not installed. Nor does it occur if Open Sauce 4.0 is installed but I am using a graphics wrapper (either DGVoodoo2 or DXVK work). Since the crash affects both graphics cards, I'm wondering if this is the cause of the crash.

**Comment by vdwtanner** [comment]
Hi @Danfun64,

Intel is only using 9on12 in 12th gen and newer CPUs.
Nvidia isn't using the mapping layer at this time.

I'm not sure what Open Sauce is doing, but I don't think 9on12 is at fault since the crash repros on the nvidia card.
