### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by bugproof** [microsoft/D3D9On12#6]
I tried it and this is the result:

```cpp
D3D9ON12_ARGS arg = { };
arg.Enable9On12 = TRUE;
pD3d9 = Direct3DCreate9On12(D3D_SDK_VERSION, &arg, 1);
```

![image](https://user-images.githubusercontent.com/3116731/131895171-25072633-6457-46fd-805c-8d80853de397.png)

dxvk works perfectly in comparison

**Comment by jenatali** [comment]
That's not a very useful bug report 😄 Is there a way we can reproduce this?

**Comment by bugproof** [comment]
Is there any log I could upload?

**Comment by jenatali** [comment]
If you can capture an [apitrace](https://github.com/apitrace/apitrace) of the app, when running without D3D9On12, then we can see what's going wrong when it does use it.

**Comment by bugproof** [comment]
Here's the trace it's big so I had to upload it somewhere else:
https://drive.google.com/file/d/1Mp0UFFjBlBshAn14fp0qIoKoDa-OrLOO/view?usp=sharing

**Comment by jenatali** [comment]
Cool, I can reproduce it. Thanks for the trace.

**Comment by jenatali** [comment]
It looks like `D3DRS_FILLMODE` is set to garbage (`0xFAFBFCFD`). Is that supposed to have some special meaning? I suspect 9on12 is mis-interpreting this as `POINT` by shoving it into a too-small bitfield, causing us to draw all vertices as points instead of actually drawing quads.

**Comment by bugproof** [comment]
Yes it works now! Thank you. Yes it was set to garbage on initialization apparently. Weird that it worked with original d3d9.dll
