### ISSUE TITLE
Transparency issues in S.T.A.L.K.E.R. Shadow of Chernobyl

### ISSUE THREAD

**Issue by vlad54rus** [microsoft/D3D9On12#86]
Grass and trees textures are bugged with D3D9On12 when running the game on Static Lighting.
![ss_user_04-02-24_12-42-07_(l05_bar)](https://github.com/microsoft/D3D9On12/assets/22005398/7121d378-a206-466a-9ab0-1ae1dacc589b)

**Comment by vdwtanner** [comment]
Would you mind sharing a pix capture of the issue?

* Download and install the June 2010 SDK here: https://www.microsoft.com/en-ca/download/details.aspx?id=6812
* Then under `C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Utilities\bin\x64` you should find PIXWin.exe
* File -> New, then enter the path to the game's exe and select the bubble for "single frame capture whenever F12 is pressed"
* Start experiment
* Press F12 when you see the corruption, then close the game
* Pix should now have the captured frame displayed. Save that, zip it up, and attach to the bug

Thanks!

**Comment by vlad54rus** [comment]
OS is Windows 10 22H2.
Capture: https://drive.google.com/file/d/19c_Qe3QYrbiRfZajg0i5xG6TuI0po-kn

**Comment by vdwtanner** [comment]
Once that change goes in you can build d3d9on12.dll locally using the instruction in the README and then copy the dll into the same directory as the game's exe to resolve the issue this flows out through official update channels. Chances are this won't get backported to win10 though, so a local build is likely the best bet.

Note that you'll need to build the right architecture (x86 or x64) to match the architecture of the game. Easy way to tell if you should build the other one is if you still see the issue after copying in the dll.

**Comment by vlad54rus** [comment]
There is no .sln file to open and no clear instructions how to build it without Visual Studio. So how do i do this?

**Comment by vdwtanner** [comment]
Ah, looking back at the instructions it does assume familiarity with cmake [(download link)](https://cmake.org/download/). I should update that to be more explicit.

Once you've got the [WDK](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) installed, you basically just need to create a directory structure that looks like this:

<parent_folder>
- Build
- D3D9on12 (this is the cloned repo)

In powershell, etc, cd to the Build directory.
Then run `cmake ../D3D9on12/CMakeLists.txt -A <arch>` (choose replace <arch> with either x64 or Win32 to build for x64 or x86 respectively)

You should now have a .sln file in the Build directory that is configured for your setup.

**Comment by vlad54rus** [comment]
The build went without errors, but in every game i try it shows a black screen, doesn't render anything.

**Comment by vdwtanner** [comment]
Hm, could be an issue with back compat with win10 (win 10 has a subset of changes represented in this repo). When I get a chance I'll have to see if I repro that when just building from github. 

You could try reverting commit 81a58b2 (#54) since that affects presentation and came after Win10, but iirc that should be fine even when d3d9 doesn't know about it yet.

**Comment by vlad54rus** [comment]
Checked again - D3D9On12 starts working when i switch to windowed mode, but the framerate is consistently below 30 unless i turn off Vsync.
The transparency issue appears to be fixed.
Reverting 81a58b2 shows some conflicts I'm not sure how to resolve.
