### ISSUE TITLE
D3d9ond3d12.dll crashed on intel 12th graphics if the install directory is not english

### ISSUE THREAD

**Issue by MemeTao** [microsoft/D3D9On12#88]
we wrote a demo :
int main() {
     IDirect3D9* device = Direct3DCreate9(D3D_SDK_VERSION);
     return 0;
}

100% crashed on intel 12th card, and crash point is OpenAdapterxxxx:
<img width="725" alt="1" src="https://github.com/microsoft/D3D9On12/assets/26571525/3b5e5d6b-a884-413b-b00a-5d054e6d457c">

 I didn't call Direct3DCreate9On12 api, how to avoid using d3d9ond3d12.dll? 

NOTE: It only crashes when the path is Chinese.

Platform: win11

**Comment by MemeTao** [comment]
![Uploading 1.png…]()

**Comment by jenatali** [comment]
This crash is inside the Intel driver.
