### ISSUE TITLE
Direct3DCreate9Createdevice failed.

### ISSUE THREAD

**Issue by ShylilyC** [microsoft/D3D9On12#92]
Strange question
![童貞兄妹_CN_5lcweWzvH4](https://github.com/microsoft/D3D9On12/assets/133392204/4464b49b-203d-4a5f-a0b9-22450002c047)

**Comment by vdwtanner** [comment]
Can you add some context to this? Are you using Direct3D9on12, or are you just trying to create a direct3d9 device directly?

**Comment by vdwtanner** [comment]
Closing as not enough information to be actionable.
